export const COLORS = {
  white: '#ffffff',
  black: '#000000',
  green: '#00AC76',
  red: '#C04345',
  blue: '#00B4D8',
  backgroundLight: '#F0F0F3',
  backgroundMedium: '#B9B9B9',
  backgroundDark: '#777777',
};

export const Items =[
    {
        id : 1, 
        category : 'in-ear',
        productName : 'Blon Bl03 Bùa Xanh',
        price : 599,
        description : 'Best in-ear dưới 1 tỉ | bùa xanh | Bl03',
        isDiscount : true,
        discount : 10,
        isAvailable : true, 
        productImage : require('../DummyData/images/inear/buaxanh2.jpg'),
        productImageList : [
            require('../DummyData/images/inear/buaxanh1.jpg'),
            require('../DummyData/images/inear/buaxanh3-1.jpg'),
            require('../DummyData/images/inear/buaxanh3.jpg'),
            require('../DummyData/images/inear/buaxanh2.jpg'),
        ],
    },
     {
        id : 2, 
        category : 'in-ear',
        productName : 'KZ In-ear Headphone',
        price : 1099,
        description : 'Best in-ear dưới 1 tỉ | KZ | Hifi headphone',
        isDiscount : false,
        isAvailable : true, 
        productImage : require('../DummyData/images/inear/kz1-4.jpg'),
        productImageList : [
            require('../DummyData/images/inear/kz1.jpg'),
            require('../DummyData/images/inear/kz1-3.jpg'),
            require('../DummyData/images/inear/kz1-4.jpg'),
            require('../DummyData/images/inear/kz1-5.jpg'),
        ],
    },
      {
        id : 3, 
        category : 'in-ear',
        productName : 'MoonDrop SSP & SSR',
        price : 1599,
        description : 'Best in-ear dưới 1 tỉ | Moondrop | Hifi headphone | SSP SSR',
        isDiscount : true,
        discount : 30, 
        isAvailable : true, 
        productImage : require('../DummyData/images/inear/ssp1.jpg'),
        productImageList : [
            require('../DummyData/images/inear/ssp1-2.jpg'),
            require('../DummyData/images/inear/ssp1-3.jpg'),
            require('../DummyData/images/inear/ssp1.jpg'),
        ],
    },
      {
        id : 4, 
        category : 'in-ear',
        productName : 'TRN TA1 In-ear Headphone',
        price : 799,
        description : 'Best in-ear dưới 1 tỉ | TRN | con rơi của đại đế sony Z1R | wibu headphone',
        isDiscount : true,
        discount : 20,
        isAvailable : false, 
        productImage : require('../DummyData/images/inear/ta1.jpg'),
        productImageList : [
            require('../DummyData/images/inear/ta1-2.jpg'),
            require('../DummyData/images/inear/ta1-3.jpg'),
            require('../DummyData/images/inear/ta1-4.jpg'),
        ],
    },
     {
        id : 5, 
        category : 'earbud',
        productName : 'Boat Earbud Headphone',
        price : 1499,
        description :  'BoAt Rockerz 450 M is an on-ear wireless headset that has been ergonomically designed to meet the needs of music lovers.',
        isDiscount : false,
        isAvailable : true, 
        productImage : require('../DummyData/images/earbud/boat1.png'),
        productImageList : [
            require('../DummyData/images/earbud/boat1.png'),
            require('../DummyData/images/earbud/boat2.png'),
             require('../DummyData/images/earbud/boat3.png'),
        ],
    },
     {
        id : 6, 
        category : 'earbud',
        productName : 'Xiaomi Earbud Headphone',
        price : 999,
        description :  'Up to 20 hours battery life | Super powerful Bass | 40mm dynamic driver | Pressure less ear muffs | Bluetooth 5.0 | Voice control.',
        isDiscount : true,
        discount : 10,
        isAvailable : true, 
        productImage : require('../DummyData/images/earbud/Mi1.png'),
        productImageList : [
            require('../DummyData/images/earbud/Mi1.png'),
            require('../DummyData/images/earbud/Mi2.png'),
             require('../DummyData/images/earbud/Mi3.png'),
        ],
    },
    {
        id : 8, 
        category : 'earbud',
        productName : 'Boult Earbud Headphone',
        price : 1199,
        description :  'Up to 40 hours battery life | 10mm dynamic driver | Pressure less ear muffs | Bluetooth 5.0 | Voice control.',
        isDiscount : true,
        discount : 30,
        isAvailable : false, 
        productImage : require('../DummyData/images/earbud/boult1.png'),
        productImageList : [
            require('../DummyData/images/earbud/boult1.png'),
            require('../DummyData/images/earbud/boult2.png'),
             require('../DummyData/images/earbud/boult3.png'),
        ],
    },
     {
        id : 7, 
        category : 'earbud',
        productName : 'Tingo Tc200 - Siêu Earbud',
        price : 199,
        description :  'Tingo tc200 custom earbud headphone with powerfull experience in budget choice',
        isDiscount : false,
        isAvailable : true, 
        productImage : require('../DummyData/images/earbud/tc200.jpg'),
        productImageList : [
            require('../DummyData/images/earbud/tc200-1.jpg'),
            require('../DummyData/images/earbud/tc200-2.jpg'),
            require('../DummyData/images/earbud/tc200-3.jpg'),
            require('../DummyData/images/earbud/tc200-4.jpg'),
        ],
    },
];